export default class AnimalSchema {
  static schema = {
    name: 'Animal',
    primaryKey: 'id',
    properties: {
      id: 'string',
      dt_minima: 'date',
      nome: 'string',
      id_animal: 'string',
      id_lote: 'int',
      id_situacao_vaca: 'int',
      id_categoria_animal: 'int',
      id_brinco_eletronico: 'string',
      id_rastreabilidade: 'int',
      id_rastreabilidade_manejo: 'int',
      peso: 'string',
      primeira_pesagem_safra: 'string',
      dt_carencia_abate: 'date',
      dt_nascimento: 'date',
      dt_ultima_pesagem: 'date',
      dt_pesagem_safra: 'date',
      id_tipo_chifre: 'int',
      id_cor_pelagem: 'int',
      id_raca: 'int',
      id_sexo: 'int',
      id_vaca: 'int',
      id_touro: 'int',
      pai: 'string',
      mae: 'string',
      crias: 'string',
      sexo: 'string',
      lote_atual: 'string',
      raca: 'string',
      pelagem: 'string',
      tipo_chifre: 'string',
      detalhes: 'string',
    }
  }
}